### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by gambhirsharma** [iftekharanwar/Design#1]
I am Gambhir. It's not an appropriate way to message you but, I didn't receive any replies from your LinkedIn and Instagram. So I took this way of approaching you. I wanted some help regarding the Logic Section for TOLC-I/TIL-I. As you mentioned on KalingaEuro YouTube video there is a good video on discrete mathematics. Can you send me the link/name of the video? Also, can you accept my request from other social so that I can have further conversations? 

Note: I think you did not configure your git email. First I tried finding your email from Github API but did not find. 
`git config user.email "YOUR_EMAIL"`

Thank you, and sorry if you find this method disturbing your GitHub workflow.

**Comment by iftekharanwar** [comment]
Hello @gambhirsharma,

I appreciate your message, and I'm here to help. I've also accepted your request; it was indeed a thoughtful approach. Haha! I will do my best to assist you in understanding the exam pattern and identifying the key topics to focus on so that you can achieve a higher score and secure your position.
